[project]
name = "gm-on-stacks"
description = "Say GM and mint GM NFTs on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.gm]
path = "contracts/gm.clar"
clarity_version = 2
epoch = 2.5

[contracts.sip-009-trait]
path = "contracts/sip-009-trait.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
